# Nombre de la aplicacion
spring.application.name=chancla-lite-auth

# Perfil activo por defecto (se sobreescribe con la variable SPRING_PROFILES_ACTIVE)
spring.profiles.active=dev

# Jackson
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false

# JWT
jwt.secret=dev-secret-local-no-usar-en-prod
jwt.expirationMillis=86400000

# Swagger habilitado por defecto (se deshabilita en prod)
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

# Cloudinary local placeholders
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:tu-cloud-name}
cloudinary.api-key=${CLOUDINARY_API_KEY:tu-api-key}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:tu-api-secret}
