# Nombre de la aplicacion
spring.application.name=chancla-lite-auth

# MariaDB - Variables desde Render
spring.datasource.url=jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.open-in-view=false
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false

# Swagger / OpenAPI - Deshabilitado en producción por seguridad
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=false

# JWT (seguridad)
jwt.secret=${JWT_SECRET}
jwt.expirationMillis=86400000

# CORS - Render
cors.allowed.origins=${FRONTEND_URL}

# Tomcat
server.tomcat.threads.max=250
server.tomcat.threads.min-spare=10

# Puerto
server.port=${PORT:8080}

# Logging
logging.level.root=INFO
logging.level.com.chancla=INFO
